"""NINA Semantic Commit Indexer (OBS-002)"""
import re
import sys
import subprocess
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
OUTPUT_FILE = REPO_ROOT / "nina_commit_index.md"

# Regular expression to extract prefix, optional scope, and subject
# format: prefix(scope): subject or prefix: subject
COMMIT_RE = re.compile(r'^([a-z]+)(?:\(([^)]+)\))?:\s*(.*)$')

# Regex to find task IDs in commit subjects or full commit subjects
# e.g. R-77, F-04, WIRE-3, OBS-001, CTX-001, PIPE-JULES-001B, BATCH-FEATURES-001
TASK_ID_RE = re.compile(
    r'\b(?:R-\d+|F-0\d|WIRE-\d+|OBS-\d+|CTX-\d+|PIPE-[A-Z]+-\d+[A-Z]*|[A-Z]+-\d+)\b',
    re.IGNORECASE
)

# Supported semantic prefixes
VALID_PREFIXES = {"fix", "feat", "ops", "chore", "docs", "sec", "infra", "core"}

def generate_index():
    try:
        # Get up to 200 commits
        cmd = ["git", "log", "--format=%H|%ai|%s", "-200"]
        res = subprocess.run(cmd, capture_output=True, text=True, check=True, cwd=str(REPO_ROOT))
    except Exception as e:
        print(f"Error running git log: {e}", file=sys.stderr)
        sys.exit(1)

    lines = res.stdout.strip().splitlines()
    entries = []

    for line in lines:
        if not line:
            continue
        parts = line.split("|", 2)
        if len(parts) < 3:
            continue
        sha, date_str, subject = parts
        short_sha = sha[:7]
        # Format date from "2026-06-16 14:47:23 +0600" to "2026-06-16"
        date_short = date_str.split()[0] if date_str else "—"

        # Try to parse semantic commit structure
        match = COMMIT_RE.match(subject)
        if match:
            prefix = match.group(1).lower()
            scope = match.group(2) or "—"
            summary = match.group(3)
        else:
            prefix = "—"
            scope = "—"
            summary = subject

        # Search for task ID in subject
        task_match = TASK_ID_RE.findall(subject)
        task_id = task_match[0].upper() if task_match else "—"

        # Validate prefix
        if prefix != "—" and prefix not in VALID_PREFIXES:
            # Fallback if prefix isn't standard but matches regex
            pass

        entries.append({
            "task_id": task_id,
            "sha": short_sha,
            "type": prefix,
            "scope": scope,
            "date": date_short,
            "summary": summary
        })

    # Write nina_commit_index.md
    now_str = datetime.now().isoformat()
    content = [
        "# NINA Commit Index — Auto-Generated",
        "## do not edit manually | regenerated by nina_commit_index.py",
        f"## last updated: {now_str}",
        "",
        "| Task ID | SHA (short) | Type | Scope | Date | Summary |",
        "|---|---|---|---|---|---|",
    ]

    for entry in entries:
        content.append(
            f"| {entry['task_id']} | {entry['sha']} | {entry['type']} | {entry['scope']} | {entry['date']} | {entry['summary']} |"
        )

    try:
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write("\n".join(content) + "\n")
    except Exception as e:
        print(f"Error writing output file: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    generate_index()
    print("Commit index updated → nina_commit_index.md")
