#!/usr/bin/env bash
# ============================================================
#  NINA docs/space/ CLEANUP — 1-click purge of stale files
#  Run from: ~/nina
#  Usage: bash nina_space_cleanup.sh
# ============================================================
set -euo pipefail

REPO="$HOME/nina"
cd "$REPO"

echo "=== NINA docs/space/ Cleanup ==="
git pull --ff-only

STALE_FILES=(
  # Perplexity-specific superseded
  "docs/space/perplexity_handoff.md"
  "docs/space/perplexity_request_template.md"

  # Jules planning artifacts (superseded by jules_backlog.md)
  "docs/space/jules_batch_manifest_p1.md"
  "docs/space/jules_batch_plan_p1.md"
  "docs/space/jules_feedback_loop.md"
  "docs/space/jules_pipeline_audit.md"
  "docs/space/jules_queue.md"
  "docs/space/jules_task_tracker.md"
  "docs/space/jules_weekly_audit.md"

  # Point-in-time audit/output snapshots
  "docs/space/nina_full_audit_report.md"
  "docs/space/nina_repo_hygiene_dashboard.md"
  "docs/space/nina_audit_log.jsonl"
  "docs/space/nina_debug_out.txt"
  "docs/space/ndev_upload_history.md"
  "docs/space/NINA_UPDATE_LOG.md"
  "docs/space/nina_megatask_index.md"
  "docs/space/nina_governance_dashboard.md"
  "docs/space/agy_prompts_batch5.md"
  "docs/space/kimi_agent_swarm.md"
  "docs/space/gemini_shim_spec.md"
  "docs/space/conversation_with_nina.md"
  "docs/space/nexus_discoveries.md"

  # Large reports (superseded)
  "docs/space/NINA_Autonomous_Super_Intelligence_Report.md"
  "docs/space/Autonomous_Super_Int.md"
  "docs/space/NINA_COMPONENT_FEATURE_LIST.md"

  # Architecture superseded
  "docs/space/nina_architecture_diagram.md"

  # Blueprint superseded
  "docs/space/four_pillar_hardening_blueprint.md"

  # Opencode superseded by NDEV.md
  "docs/space/opencode_audit_protocol.md"
  "docs/space/OPENCODE_INTEGRATION.md"

  # Ninaflash stub (real file exists)
  "docs/space/ninaflash_stub.md"
  "docs/space/ninaflash_task_tracker.md"

  # Giant auto-generated indexes (regenerated by nina_sync.sh)
  "docs/space/nina_index.md"
  "docs/space/nina_index.json"
  "docs/space/nina_file_registry.json"
)

DELETED=0
SKIPPED=0

for f in "${STALE_FILES[@]}"; do
  if [ -f "$REPO/$f" ]; then
    git rm -f "$f"
    echo "  ✓ removed: $f"
    DELETED=$((DELETED+1))
  else
    echo "  ○ already gone: $f"
    SKIPPED=$((SKIPPED+1))
  fi
done

echo ""
echo "── Summary ─────────────────────────"
echo "  Deleted : $DELETED"
echo "  Skipped : $SKIPPED (already clean)"
echo ""

if [ "$DELETED" -gt 0 ]; then
  git commit -m "chore(docs): purge stale docs/space files

Removed $DELETED stale/superseded files:
- Point-in-time audit snapshots
- Superseded Jules planning artifacts
- Old architecture/opencode/ninaflash stubs
- Auto-generated indexes (nina_index.md/json, nina_file_registry.json)

Survivors: NDEV.md, PERPLEXITY_SPACE_INSTRUCTIONS.md, jules_backlog.md,
nina_error_register.md, nina_contract.md, nina_session_brief.md,
nina_state.md, DELTA_SYNC_PROTOCOL.md, FEATURES.md, nina_runbook.md"
  git push
  echo "✅ Done! $DELETED files removed and pushed."
else
  echo "✅ Already clean — nothing to remove."
fi
