import os, sys, json, subprocess, argparse
from pathlib import Path
from datetime import datetime

def run_cmd(cmd):
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.stdout.splitlines()

def get_git_tracked():
    return set(run_cmd(["git", "ls-files"]))

def get_stale_files(months=6):
    recent = set(run_cmd(["git", "log", f"--since={months} months ago", "--pretty=format:", "--name-only"]))
    # git log outputs empty lines sometimes
    recent = {f for f in recent if f}
    tracked = get_git_tracked()
    return tracked - recent

def get_fs_all(repo_root):
    fs_all = set()
    ignore_parts = {".git", "venv", ".venv", "__pycache__", ".pytest_cache", ".mypy_cache", ".agent", ".jules", "node_modules", ".aider.tags.cache"}
    
    for root, dirs, files in os.walk(repo_root):
        # Prune dirs
        dirs[:] = [d for d in dirs if d not in ignore_parts and not d.startswith(".aider")]
        for file in files:
            if file.startswith(".aider"):
                continue
            full_path = Path(root) / file
            rel_path = full_path.relative_to(repo_root)
            fs_all.add(str(rel_path))
    return fs_all

def notify_telegram(message):
    bot_token = os.environ.get("TELEGRAMBOTTOKEN")
    chat_id = os.environ.get("TELEGRAMCHATID")
    if not bot_token or not chat_id:
        print("⚠️  Telegram credentials not found in environment. Skipping notification.")
        return
        
    import urllib.request
    import urllib.parse
    
    url = f"https://api.telegram.org/bot{bot_token}/sendMessage"
    data = urllib.parse.urlencode({'chat_id': chat_id, 'text': message, 'parse_mode': 'Markdown'}).encode('utf-8')
    
    try:
        req = urllib.request.Request(url, data=data)
        with urllib.request.urlopen(req) as response:
            if response.status == 200:
                print("✅ Telegram notification sent successfully.")
            else:
                print(f"❌ Failed to send Telegram notification: {response.status}")
    except Exception as e:
        print(f"❌ Exception sending Telegram notification: {e}")

def audit(strict=False, notify=False):

    repo_root = Path(__file__).parent.parent.resolve()
    
    # 1. Gather data
    git_tracked = get_git_tracked()
    fs_all = get_fs_all(repo_root)
    stale_tracked = get_stale_files(months=6)
    
    # Load index to know what's governed
    index_path = repo_root / "docs/space/nina_index.json"
    governed_paths = set()
    if index_path.exists():
        with open(index_path) as f:
            idx_data = json.load(f)
            governed_paths = {f["path"] for f in idx_data.get("files", []) if f.get("governed")}

    # 2. Reconcile
    stray_locals = fs_all - git_tracked
    missing_locally = git_tracked - fs_all
    
    # Categorize severity
    hard_violations = []
    warnings = []
    
    # Missing locally is always a hard violation if it's a real file we expect
    for f in missing_locally:
        hard_violations.append(f"Missing locally (corrupted worktree): {f}")
        
    # Governed files that are untracked (stray locals in governed paths)
    for f in stray_locals:
        p = Path(f)
        if p.parts[0] in ["core", "tools", "interfaces", "docs", "crons", "agent", "ninagate", "checks"]:
            if not f.endswith(".bak") and not f.endswith(".pyc") and not f.endswith(".log"):
                hard_violations.append(f"Untracked file in governed directory: {f}")
            else:
                warnings.append(f"Transient local in governed directory: {f}")
        else:
            warnings.append(f"Stray local (untracked): {f}")
            
    # Stale files
    stale_governed = []
    for f in stale_tracked:
        if f in governed_paths:
            stale_governed.append(f)
            warnings.append(f"Stale governed file (>6 months): {f}")

    # 3. Generate Dashboard
    md = f"""# NINA Repository Hygiene Dashboard
_Generated by `tools/audit_repo_hygiene.py` on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_

## 1. Hygiene Status
- **Git Tracked Files:** {len(git_tracked)}
- **Stray Locals (Untracked):** {len(stray_locals)}
- **Missing Locally:** {len(missing_locally)}
- **Stale Governed Files (>6 months):** {len(stale_governed)}

## 2. Hard Violations (Blocks CI)
"""
    if not hard_violations:
        md += "✅ None.\n"
    else:
        for v in hard_violations:
            md += f"- ❌ {v}\n"

    md += "\n## 3. Stale Governed Files (Action Required)\n"
    if not stale_governed:
        md += "✅ None.\n"
    else:
        for f in sorted(stale_governed):
            md += f"- ⚠️ `{f}` (Consider archival or check if dead code)\n"
            
    md += "\n## 4. Stray Locals (Top 20)\n"
    if not stray_locals:
        md += "✅ None.\n"
    else:
        for f in sorted(list(stray_locals))[:20]:
            md += f"- 🗑️ `{f}`\n"
            
    if len(stray_locals) > 20:
        md += f"- ... and {len(stray_locals) - 20} more.\n"

    with open(repo_root / "docs/space/nina_repo_hygiene_dashboard.md", "w") as f_out:
        f_out.write(md)

    print("✅ Hygiene audit complete. Dashboard generated at docs/space/nina_repo_hygiene_dashboard.md")
    
    if notify and hard_violations:
        from dotenv import load_dotenv
        load_dotenv(repo_root / ".env")
        msg = f"🚨 *NINA Governance Alert*\n\nHygiene audit detected *{len(hard_violations)}* hard violations.\nCheck `docs/space/nina_repo_hygiene_dashboard.md` for details."
        notify_telegram(msg)

    if strict and hard_violations:
        print("\n❌ STRICT MODE: Hard violations detected. Failing pipeline.")
        for v in hard_violations:
            print(f"  - {v}")
        sys.exit(1)
    
    if hard_violations:
        print(f"\n⚠️ WARNING: {len(hard_violations)} hard violations detected. (Run with --strict to fail).")
        
    return True

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true", help="Fail with non-zero exit code on hard violations")
    parser.add_argument("--notify", action="store_true", help="Send Telegram alerts on violations")
    args = parser.parse_args()
    audit(args.strict, args.notify)
