#!/usr/bin/env python3
"""tools/gen_claude_feed.py — Generate docs/space/claude_feed.md

Extracted from scripts/nina_sync.sh v6.2 (_bg_worker heredoc).
Skips regeneration if last 5 commits are unchanged since last run.

Usage:
  python3 tools/gen_claude_feed.py
  python3 tools/gen_claude_feed.py --force
"""
import argparse
import subprocess
import time
from pathlib import Path

NINA = Path(__file__).parent.parent
OUT = NINA / "docs/space/claude_feed.md"
BACKLOG = NINA / "docs/space/jules_backlog.md"
LOCK = NINA / "juleslock.txt"
STAMP = NINA / "logs/.claude_feed_stamp"


def _git(cmd: str) -> str:
    return subprocess.getoutput(f"cd {NINA} && {cmd}").strip()


def _needs_regen(force: bool) -> bool:
    """Skip if the last-5-commit SHA hasn't changed since last run."""
    if force:
        return True
    current_sha = _git("git log --oneline -5 | md5sum | cut -c1-12")
    if STAMP.exists() and STAMP.read_text().strip() == current_sha:
        return False
    return True


def _write_stamp() -> None:
    STAMP.parent.mkdir(parents=True, exist_ok=True)
    current_sha = _git("git log --oneline -5 | md5sum | cut -c1-12")
    STAMP.write_text(current_sha)


def generate(force: bool = False) -> bool:
    """Generate claude_feed.md. Returns True if written, False if skipped."""
    if not _needs_regen(force):
        return False

    import re

    lines = [
        "# NINA Claude Feed — Session Startup Context",
        "> Auto-generated by tools/gen_claude_feed.py — do not edit manually",
        "> Claude: read this. Then generate 10 non-overlapping Jules specs.\n",
    ]

    head = _git("git log -1 --pretty='%H|%s|%ci'").split("|")
    lines += [
        "## 1. Snapshot",
        f"- Generated: {time.strftime('%Y-%m-%d %H:%M %Z')}",
        f"- Git HEAD: {head[0] if head else 'unknown'}",
        f"- Last commit: {head[1] if len(head) > 1 else 'unknown'}",
        f"- Service: {subprocess.getoutput('systemctl --user is-active nina 2>/dev/null || echo unknown').strip()}",
    ]

    lines += ["## 2. Locked Files"]
    lines.append(
        f"```\n{LOCK.read_text().strip()}\n```"
        if LOCK.exists() and LOCK.read_text().strip()
        else "- None"
    )

    lines += ["## 3. READY Items"]
    if BACKLOG.exists():
        blocks = re.findall(
            r"((?:###|####).+?(?=###|####|\Z))", BACKLOG.read_text(), re.DOTALL
        )
        ready = [b.strip() for b in blocks if "READY" in b][:20]
        lines.append(f"_{len(ready)} READY items_\n")
        for b in ready:
            lines.append(b[:400])
            lines.append("")

    lines += [
        "## 4. Last 5 Commits",
        "```",
        _git("git log --oneline -5"),
        "```",
    ]

    lines += ["## 5. PRs Open"]
    pr_out = subprocess.getoutput(
        "gh pr list --state open --json number,title,headRefName "
        "--jq '.[] | \"#\\(.number) \\(.title) [\\(.headRefName)]\"' 2>/dev/null || echo 'gh unavailable'"
    ).strip()
    lines.append(pr_out or "- None")

    OUT.write_text("\n".join(lines))
    _write_stamp()
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate claude_feed.md")
    parser.add_argument("--force", action="store_true", help="Regenerate even if commits unchanged")
    args = parser.parse_args()
    written = generate(force=args.force)
    print("claude_feed: written" if written else "claude_feed: skipped (no new commits)")
