import json, os
from pathlib import Path
from datetime import datetime

def generate():
    repo_root = Path("/home/aibony/nina")
    index_path = repo_root / "docs/space/nina_index.json"
    
    if not index_path.exists():
        print("❌ nina_index.json not found. Run update_index.py first.")
        return
        
    with open(index_path) as f:
        data = json.load(f)
        
    files = data["files"]
    clusters = data.get("duplicate_clusters", [])
    
    # Metrics
    total_score = 0
    missing_tests = []
    requires_tests_count = 0
    purge_candidates = []
    low_quality = []
    
    guardrail_counts = {"high_risk_do_not_edit_directly": 0, "append_only": 0, "read_only_for_agents": 0}
    guardrail_lists = {"high_risk_do_not_edit_directly": [], "append_only": [], "read_only_for_agents": []}
    
    for f in files:
        score = 0
        if f.get("summary") and f["summary"] != "Governed artifact.": score += 1
        if f.get("role"): score += 1
        if f.get("origin"): score += 1
        if f.get("retention_policy"): score += 1
        if f.get("tags"): score += 1
        quality = (score / 5.0) * 100
        total_score += quality
        low_quality.append((f["path"], quality))
        
        if f.get("requires_tests"):
            requires_tests_count += 1
            p = Path(f["path"])
            test_path = repo_root / "tests" / f"test_{p.stem}.py"
            if not test_path.exists() and not any(p.stem in t for t in os.listdir(repo_root / "tests")):
                missing_tests.append(f["path"])
                
        if f.get("retention_policy") in ["purge_candidate", "ephemeral"]:
            purge_candidates.append(f["path"])
            
        for gr in f.get("guardrails", []):
            if gr in guardrail_counts:
                guardrail_counts[gr] += 1
                guardrail_lists[gr].append(f["path"])
                
    avg_quality = total_score / len(files) if files else 0
    low_quality.sort(key=lambda x: x[1])
    
    # Generate Markdown
    md = f"""# NINA Governance Dashboard
_Generated by `tools/generate_dashboard.py` on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_

## 1. Summary Metrics
- **Metadata Completeness:** {avg_quality:.1f}% (Threshold: 75.0%)
- **Governed Files:** {len(files)}
- **Duplicate Clusters:** {len(clusters)}
- **Purge Candidates:** {len(purge_candidates)}
- **Files Requiring Tests:** {requires_tests_count}
- **Files Missing Obvious Tests:** {len(missing_tests)}

## 2. Hotspots

### Top 10 Missing-Test Files
"""
    for p in missing_tests[:10]:
        md += f"- `{p}`\n"
        
    md += "\n### Top 10 Lowest Metadata Quality\n"
    for p, q in low_quality[:10]:
        md += f"- `{p}` ({q:.0f}%)\n"
        
    md += "\n### Top Duplicate Clusters\n"
    sorted_clusters = sorted(clusters, key=lambda c: len(c["members"]), reverse=True)
    for c in sorted_clusters[:5]:
        md += f"- `{c['cluster_id']}` ({len(c['members'])} members) -> Canonical: `{c['canonical_path']}`\n"

    md += "\n### Top Purge Candidates & Ephemeral Paths\n"
    for p in purge_candidates[:5]:
        md += f"- `{p}`\n"
        
    md += "\n## 3. Guardrail Hotspots\n"
    for gr in ["high_risk_do_not_edit_directly", "append_only", "read_only_for_agents"]:
        md += f"- **{gr}** ({guardrail_counts[gr]} files): " + ", ".join([f"`{p}`" for p in guardrail_lists[gr][:3]]) + ("..." if guardrail_counts[gr] > 3 else "") + "\n"
        
    md += """
## 4. Recommended Actions
1. **Testing:** Write tests for the top missing-test files to improve system resilience.
2. **Cleanup:** Run `python3 tools/cleanup_by_index.py` and review output to clear purge candidates.
3. **Metadata:** Enrich summaries for the lowest quality metadata files in `tools/update_index.py`.
"""
    
    with open(repo_root / "docs/space/nina_governance_dashboard.md", "w") as f_out:
        f_out.write(md)
        
    print("✅ Dashboard generated at docs/space/nina_governance_dashboard.md")

if __name__ == "__main__":
    generate()
