#!/usr/bin/env python3
"""
nina_commit_index.py — generate docs/generated/nina_commit_index.md
Output path: docs/generated/nina_commit_index.md  (NOT repo root)

Fix: null byte in format string caused subprocess ValueError on Python 3.14.
Solution: pass format via env var, not inline shell string.
"""
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent
OUTPUT = ROOT / "docs" / "generated" / "nina_commit_index.md"


def get_git_log(n: int = 200) -> list[dict]:
    """Use --format with simple delimiter to avoid null byte issues."""
    try:
        raw = subprocess.check_output(
            [
                "git", "log",
                "--pretty=format:%H|||%h|||%aI|||%an|||%s",
                f"-{n}",
            ],
            stderr=subprocess.DEVNULL,
            text=True,
            cwd=str(ROOT),
        )
    except subprocess.CalledProcessError:
        return []
    entries = []
    for line in raw.strip().splitlines():
        if not line.strip():
            continue
        parts = line.split("|||")
        if len(parts) >= 5:
            entries.append({
                "sha":     parts[0].strip(),
                "short":   parts[1].strip(),
                "date":    parts[2].strip()[:10],
                "author":  parts[3].strip(),
                "subject": "|||".join(parts[4:]).strip(),
            })
    return entries


def build_md(entries: list[dict]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# NINA Commit Index",
        "",
        f"> Auto-generated by `nina_commit_index.py` \u2014 {now}  ",
        f"> Output: `docs/generated/nina_commit_index.md` (gitignored)",
        "",
        "| # | Date | SHA | Author | Subject |",
        "|---|------|-----|--------|---------|",
    ]
    for i, e in enumerate(entries, 1):
        subj = e["subject"].replace("|", "\\|")
        lines.append(f"| {i} | {e['date']} | `{e['short']}` | {e['author']} | {subj} |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 200
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    entries = get_git_log(n)
    if not entries:
        print("WARN: no commits found (not a git repo or git error)")
        sys.exit(0)
    OUTPUT.write_text(build_md(entries))
    print(f"\u2713 Written: {OUTPUT} ({len(entries)} commits)")
